[2022-01-26 20:38:42,004] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 20:38:42,015] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 20:38:42,015] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 20:38:42,016] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-26 20:38:42,016] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 20:38:42,027] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-01-25 00:00:00+00:00
[2022-01-26 20:38:42,032] {standard_task_runner.py:52} INFO - Started process 5262 to run task
[2022-01-26 20:38:42,035] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2022-01-25T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp92av5qgy', '--error-file', '/tmp/tmpxh4n47l_']
[2022-01-26 20:38:42,036] {standard_task_runner.py:77} INFO - Job 36: Subtask download_dataset_task
[2022-01-26 20:38:42,085] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [running]> on host 9fb8ae766f9d
[2022-01-26 20:38:42,134] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T00:00:00+00:00
[2022-01-26 20:38:42,135] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-26 20:38:42,136] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-01-26 20:38:42,145] {subprocess.py:85} INFO - Output:
[2022-01-26 20:38:42,263] {subprocess.py:89} INFO - curl: (6) Could not resolve host: s3.amazonaws.com
[2022-01-26 20:38:42,264] {subprocess.py:93} INFO - Command exited with return code 6
[2022-01-26 20:38:42,276] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-01-26 20:38:42,283] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20220125T000000, start_date=20220126T203842, end_date=20220126T203842
[2022-01-26 20:38:42,297] {standard_task_runner.py:92} ERROR - Failed to execute job 36 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-01-26 20:38:42,327] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-26 20:38:42,360] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-26 20:57:01,341] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 20:57:01,354] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 20:57:01,354] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 20:57:01,355] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-26 20:57:01,355] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 20:57:01,367] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-01-25 00:00:00+00:00
[2022-01-26 20:57:01,371] {standard_task_runner.py:52} INFO - Started process 150 to run task
[2022-01-26 20:57:01,374] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2022-01-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpmc887apm', '--error-file', '/tmp/tmpe2spj5xh']
[2022-01-26 20:57:01,375] {standard_task_runner.py:77} INFO - Job 3: Subtask download_dataset_task
[2022-01-26 20:57:01,423] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [running]> on host 09b8c78ea44a
[2022-01-26 20:57:01,471] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T00:00:00+00:00
[2022-01-26 20:57:01,472] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-26 20:57:01,473] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-01-26 20:57:01,482] {subprocess.py:85} INFO - Output:
[2022-01-26 20:57:28,373] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-26 20:57:28,966] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20220125T000000, start_date=20220126T205701, end_date=20220126T205728
[2022-01-26 20:57:29,011] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-26 20:57:29,044] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-26 22:25:40,896] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 22:25:40,907] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 22:25:40,907] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 22:25:40,908] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-26 22:25:40,908] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 22:25:40,919] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-01-25 00:00:00+00:00
[2022-01-26 22:25:40,923] {standard_task_runner.py:52} INFO - Started process 127 to run task
[2022-01-26 22:25:40,926] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2022-01-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmprdx52gpv', '--error-file', '/tmp/tmp2shk4cy2']
[2022-01-26 22:25:40,928] {standard_task_runner.py:77} INFO - Job 3: Subtask download_dataset_task
[2022-01-26 22:25:40,982] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [running]> on host 062265fab11f
[2022-01-26 22:25:41,031] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T00:00:00+00:00
[2022-01-26 22:25:41,033] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-26 22:25:41,034] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-01-26 22:25:41,043] {subprocess.py:85} INFO - Output:
[2022-01-26 22:26:19,289] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-26 22:26:20,578] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20220125T000000, start_date=20220126T222540, end_date=20220126T222620
[2022-01-26 22:26:20,620] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-26 22:26:20,672] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-26 22:34:10,074] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 22:34:10,085] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-01-26 22:34:10,086] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 22:34:10,086] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-26 22:34:10,086] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-26 22:34:10,102] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-01-25 00:00:00+00:00
[2022-01-26 22:34:10,106] {standard_task_runner.py:52} INFO - Started process 105 to run task
[2022-01-26 22:34:10,109] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2022-01-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpigpzn5d2', '--error-file', '/tmp/tmpcfwrcjd9']
[2022-01-26 22:34:10,110] {standard_task_runner.py:77} INFO - Job 3: Subtask download_dataset_task
[2022-01-26 22:34:10,156] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-01-25T00:00:00+00:00 [running]> on host 23953897a00d
[2022-01-26 22:34:10,202] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T00:00:00+00:00
[2022-01-26 22:34:10,203] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-26 22:34:10,204] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-01-26 22:34:10,213] {subprocess.py:85} INFO - Output:
[2022-01-26 22:35:33,799] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-26 22:35:33,821] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20220125T000000, start_date=20220126T223410, end_date=20220126T223533
[2022-01-26 22:35:33,878] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-26 22:35:33,913] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
